# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170613_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='place',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='win_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
