# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170623_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='user',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Pick',
        ),
    ]
