# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_picked',
            field=models.BooleanField(default=False),
        ),
    ]
