# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_league_user_linkage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_user_linkage',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='league_user_linkage',
            name='user',
        ),
        migrations.DeleteModel(
            name='League_User_Linkage',
        ),
    ]
