# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170710_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='profile',
        ),
    ]
