# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_record_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Record'),
        ),
    ]
