# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_profile_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='place',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
