# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_schedule_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
