# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-30 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20170730_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='away_team',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home_team',
            field=models.BigIntegerField(default=1),
        ),
    ]
