# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-30 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20170730_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='away_team',
            new_name='opponent',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='home_team',
            new_name='user',
        ),
    ]
