# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-30 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20170730_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user',
            new_name='user_id',
        ),
    ]
