# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-01 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20170730_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
