# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-04 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_profile_league_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='password',
            field=models.CharField(default=b'password', max_length=50, null=True),
        ),
    ]
