# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-11 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20170804_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
