# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_league_is_open'),
        ('home', '0031_pointsforweek'),
    ]

    operations = [
    ]
