# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_merge_20170814_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='is_open',
        ),
    ]
