# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_league_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='record',
        ),
        migrations.AddField(
            model_name='record',
            name='profile',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='home.Profile'),
        ),
    ]
