# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20170826_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='opponent',
            field=models.ForeignKey(default=52, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(default=52, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
