# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
