# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0010_auto_20170702_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
