# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import picks.models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0011_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_id', models.BigIntegerField()),
                ('home_team_name', models.CharField(default=picks.models.team_name_default, max_length=50)),
                ('away_team_id', models.BigIntegerField()),
                ('away_team_name', models.CharField(default=picks.models.team_name_default, max_length=50)),
                ('winning_team_id', models.BigIntegerField(null=True)),
                ('difference_in_score', models.IntegerField(null=True)),
            ],
        ),
    ]
