# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0013_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='is_correct',
            field=models.NullBooleanField(),
        ),
    ]
