# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-04 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0014_auto_20170702_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='matchweek',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 15, 6, 24, 827795, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pick',
            name='matchweek',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 15, 6, 30, 342437, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
