# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0015_auto_20170704_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='team_picked',
            field=models.CharField(max_length=50),
        ),
    ]
