# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0016_auto_20170706_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='game_id',
        ),
        migrations.AddField(
            model_name='pick',
            name='away_team',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='home_team',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
