# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0019_auto_20170708_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='team_picked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='picks.Team'),
        ),
    ]
