# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-13 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0023_auto_20170713_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='matchweek',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='pick',
            old_name='matchweek',
            new_name='week',
        ),
    ]
