# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0024_auto_20170713_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='week',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='week',
        ),
    ]
