# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0025_auto_20170713_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pick',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
