# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-18 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import picks.models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0026_auto_20170713_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='away_team',
            field=models.CharField(default=picks.models.team_name_default, max_length=50),
        ),
        migrations.AddField(
            model_name='pick',
            name='home_team',
            field=models.CharField(default=picks.models.team_name_default, max_length=50),
        ),
    ]
