# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-18 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0027_auto_20170717_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='home_team',
        ),
        migrations.AddField(
            model_name='pick',
            name='game_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='picks.Game'),
            preserve_default=False,
        ),
    ]
