# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-18 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0029_auto_20170717_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='away_team_id',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='away_team_name',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='home_team_id',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='home_team_name',
        ),
    ]
