# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-22 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0031_pick_home_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='home_team',
        ),
    ]
