# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-26 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0033_auto_20170722_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='team_picked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks.Team'),
        ),
    ]
