# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picks', '0034_auto_20170726_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='pick',
            name='is_correct',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='pick',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pick',
            name='week',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='PickDetails',
        ),
    ]
