# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-04 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0035_auto_20170727_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='margin',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pick',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
