# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-10 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0037_auto_20170807_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='underdog',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='margin',
            field=models.IntegerField(),
        ),
    ]
