# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0038_auto_20170809_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='game',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='picks.Game'),
        ),
    ]
