# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0039_pick_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winning_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks.Team'),
        ),
    ]
