# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0041_auto_20170816_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='picks.Team'),
        ),
    ]
