# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0042_auto_20170822_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='game',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='picks.Game'),
        ),
    ]
